### ISSUE TITLE
Organize the `ltitop` project

### ISSUE THREAD

**Issue by hidmic** [hidmic/ltitop#10]
## Rationale

For `ltitop` to be anything but a one-man project, some organization has to be put in place.

## Definition of Done

- [x] Add PR template
- [x] Add issue templates
   - [x] Add feature request template
   - [x] Add bug report template 
- [ ] Add contribution guidelines.
- [ ] Add release process.
   - Use [semver](https://semver.org/) for versioning.
   - Use Github releases to publish.
- [ ] Add code of conduct
- [ ] Add roadmap (as project board?)

## Additional considerations

Evaluate Github Discussions for contributor exchanges.
