### ISSUE TITLE
Distribute `ltitop` in PyPI

### ISSUE THREAD

**Issue by hidmic** [hidmic/ltitop#11]
## Rationale

Distributing `ltitop` as a regular Python package is key to ease of use. 

Requires #12 and #13.

## Definition of Done

- [ ] Prepare project for proper [packaging](https://packaging.python.org/tutorials/packaging-projects/)
   - [ ] Populate `setup.cfg`
   - [ ] Clean up `setup.py`
   - [ ] Add `pyproject.toml`
- [ ] Add project changelog.
   - Use [gitchangelog](https://pypi.org/project/gitchangelog/) to generate it
- [ ] Use [PyPI](https://pypi.org/) to publish
