### ISSUE TITLE
Boost `ltitop` quality

### ISSUE THREAD

**Issue by hidmic** [hidmic/ltitop#12]
## Rationale

As of today, `ltitop` is still pretty much a proof-of-concept. Thus, its code needs polishing, test coverage must be increased, and a continuous integration process be put in place to ensure it stays healthy over time. 

## Definition of Done

- [x] Add [pre-commit](https://pre-commit.com/) hooks 
   - [x] Reformat sources using [black](https://github.com/psf/black) and [blacken-docs](https://github.com/asottile/blacken-docs)
   - [x] Reformat sources susing [isort](https://github.com/PyCQA/isort).
   - [x] Lint sources using [flake8](https://github.com/PyCQA/flake8).
   - [x] Statically check sources using [mypy](https://github.com/pre-commit/mirrors-mypy).
   - [x] Lint tox.ini using [tox-ini-fmt](https://github.com/tox-dev/tox-ini-fmt)
- [x] Test for Python 3.5+ using `tox`
- [ ] Measure coverage using [pytest-cov](https://pytest-cov.readthedocs.io/)
- [x] Configure Github Actions CI
    - [x] Test job to ensure all unit tests pass
    - [x] Lint job to ensure all linters pass
- [ ] Test all public APIs (~80% coverage)
- [ ] Type annotate all public APIs.

## Additional considerations

Consider [Codecov](https://docs.codecov.io) or [Coveralls](https://docs.coveralls.io/) for coverage tracking.
