### ISSUE TITLE
Build `ltitop` documentation

### ISSUE THREAD

**Issue by hidmic** [hidmic/ltitop#13]
## Rationale

As of today, `ltitop` has no documentation. That makes it useless for pretty much anyone.

## Definition of Done

- [ ] Document project public APIs
    - Use [ReST format](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) for docstrings.
- [ ] Document project itself
   - [ ] Add quickstart?
   - [ ] Add overview
   - [ ] Add purpose
   - [ ] Add tutorial?
- [ ] Build project documentation using Sphinx
   - Use [RTD theme](https://sphinx-rtd-theme.readthedocs.io/)
- [ ] Use [RTD](https://docs.readthedocs.io/en/stable/tutorial/index.html) to publish
   - Ensure rebuilds on push to `master` (use Github webhook).
- [ ] Populate README.md
   - [ ] Add short overview
   - [ ] Add project logo
   - [ ] Add badges
   - [ ] Link to docs

## Additional considerations

See this [blog post](https://towardsdatascience.com/how-to-set-up-your-python-project-docs-for-success-aab613f79626) for useful pointers.
